---
- hosts: mysofttekservers
  become: yes
  become: true
  become_user: username
  become_method: sudo
  tasks:
    - name: Install Apache Web Server
      yum: name=httpd state=latest
      notify:
        - openport80
        - startwebserver
  handlers:
    - name: openport80
      firewalld: port=80/tcp permanent=true state=enabled immediate=yes
    - name: startwebserver
      service: name=httpd state=started
    
